### PR TITLE
Replaced social media buttons with just a Sign in with Google button

### PR DESCRIPTION
**Pull request by v74c63t**
Screenshot 2023-11-17 at 12 36 28 PM

### CODE REVIEW

**Review by DerrickMac — CHANGES_REQUESTED** [review]
After doing some research, I'm not sure if the Google button follows Google's branding guidelines for the sign-in button. If I read the documentation correctly, the sign-in button needs to follow the branding guidelines for app verification purposes. 

You may need the button to look like the one on their documentation
https://developers.google.com/identity/sign-in/web/build-button
https://developers.google.com/identity/branding-guidelines

**Comment by v74c63t** [comment]
Screenshot 2023-12-01 at 12 48 17 PM
I basically just took what they had on the Google dev page and added it, but I didn't adjust the width of the button because it looks off when its stretched so I kept it small.

**Comment by DerrickMac** [comment]
For extra clarity to sign in with Google, would you be able to add a horizontal line with text 'Or' between the login button and the Sign In With Google button? 

image

**Review by DerrickMac — DISMISSED** [review]

**Review by DerrickMac — CHANGES_REQUESTED** [review]
Just so it is extra clear for users to sign in using Google, can you add a horizontal line with some kind of text like 'Or', I pasted an example below

image

**Comment by v74c63t** [comment]
Screenshot 2023-12-11 at 7 09 37 PM

**Review by DorisSanchez-Velasquez — APPROVED** [review]
approved!

**Pull request merged**
