### PR TITLE
404 WebPage Check Issue

### PR DESCRIPTION
**Pull request by SamirZelaya**
For Frontend to figure out what's happening with the code. 🤔
Issue: 404 Webpage doesn't appear.

### CODE REVIEW

**Comment by v74c63t** [comment]
Did you add a route to App.jsx to the page?

**Comment by v74c63t** [comment]
Ok so from when I checked previously and as mentioned before, I copied your file over and got it to show up as long as the route for the page was created and the page was imported in App.jsx. I ran the server and went to the endpoint assigned for that route and the text was displaying without any issues on the page. If you're still running into a blank page even after adding all of that, there might be some other issues that are happening and it would probably require a screen share or at least a couple of screenshots for others to figure out what's the problem.

**Comment by ItsJonasL** [comment]
I would like to add that I was able to get it work too. If you are on VS Code can you download the Live share or Code Snap extensions so we can help you in the next meeting?

**Comment by DorisSanchez-Velasquez** [comment]
I've gotten it to work as well. This might be a bigger issue with the dependencies on the version of the project you're working on. Recommendation would be to reinstall all dependencies and fetch everything from the main branch. Make sure you've closed the server before running these commands.

Git Commands:
**git fetch** (to fetch any cache or info from the main branch)

**git pull origin main** (to get all file changes from the main branch)

**npm install --legacy-peer-deps** (to reinstall all dependencies)

**Pull request closed without merging**
